### ISSUE TITLE
Prettify Ext. and Default Languages

### ISSUE THREAD

**Issue by cpede** [amroamroamro/prettify-matlab#5]
Sorry to write again, but I'm trying to see if prettify can be used for anything useful.

Is it correct that the `lang=matlab` needs to be set as parameter to` run_prettify.js` since MATLAB is not part of the default supported languages in prettify ?
If using e.g. c++ I do **not** need to specify` lang=cpp` since this is a default language ?
If using `pretttify.js` instead of `run_pretttify.js`, I need to link each of the non-default language js files, e.g. `lang-matlab.js` ?
But if calling just `pretttify.js` I also need to call the function `prettyPrint();` on my page to get it started ?
Why would you then ever call `pretttify.js` and not `run_pretttify.js` ?

Looking at the sample below, why is vb and c++ rendered differently ?

https://jsfiddle.net/cpede/1gkc7fjw/

Thanks for helping me.
-cpede

**Comment by amroamroamro** [comment]
> Is it correct that the `lang=matlab` needs to be set as parameter to `run_prettify.js` since MATLAB is not part of the default supported languages in prettify ?

yes, you need `<script src=".../run_prettify.js?lang=matlab">`

>  If using e.g. c++ I do not need to specify `lang=cpp` since this is a default language ?

correct, just use `<script src=".../run_prettify.js">` (in fact there is no `lang-cpp.js` file!)

As explained in the [official readme file][1], Prettify by default works for a number of languages including:

- C/C++, C#, Java, Python, Perl, Ruby, Bash, HTML, XML, JavaScript/CoffeScript

For these language, you only need the core prettify script.
Additional languages (including MATLAB) are supported via extensions. So each [`lang-*.js` file][2] adds support for an additional language. You have to explicitly pick the extensions you want to enable.

> If using `pretttify.js` instead of `run_pretttify.js`, I need to link each of the non-default language js files, e.g. `lang-matlab.js` ?

yes, you need both `<script src=".../prettify.js">` and `<script src=".../lang-matlab.js>`

> But if calling just `pretttify.js` I also need to call the function `prettyPrint();` on my page to get it started ?

yes, you must call it at some point, like `<body onload="prettyPrint();">`

> Why would you then ever call `pretttify.js` and not `run_pretttify.js` ?

There are two ways to use Prettify:

- include `prettify.js` script along with any wanted `lang-*.js` extension, in addition to a stylesheet `prettify.css` (or one of the other skins from the [`styles/` folder][3]), and run `prettyPrint()` at some point to apply syntax highlighting

- include the auto-loader script `run_prettify.js` possibly with additional parameters `run_pretttify.js?lang=..&skin=..`

Now the auto-loader is simply for convenience, and is basically doing the same thing, i.e:
- it contains the same code as the base `prettify.js` script
- if any `lang=..` are specified, it also loads additional `lang-*.js` extensions
- it either loads the default `prettify.css` stylesheet or a different .css if `skin=..` is specified
- finally it runs `prettyPrint()` function once scripts are loaded

It's worth noting that language hinting is optional (i.e the `<pre class="lang-xxx">` part, not to be confused with the language handler files `lang-xxx.js`).
By default Prettify uses sort of a generic syntax highlighting that works on most languages, but it's better to be explicit if you know the language beforehand.

[1]: https://github.com/google/code-prettify/blob/master/README.md#for-which-languages-does-it-work
[2]: https://github.com/google/code-prettify/tree/master/src
[3]: https://github.com/google/code-prettify/tree/master/styles

**Comment by cpede** [comment]
Thanks for the answer.
OK, so I'm stating to get it. However I think that it is difficult to see which filter that it used to do the syntax highlighting. I can see that the attribute `prettyprinted` is added to the `<pre>` tag after it has been processed, but you cannot see if it is using the language that you believe or if it is using a default syntax highlighting ?
If you look at my jsfiddle in my original post, I would expect that keywords, variables etc. would be the same for the C++ and JavaScript code, but it is not ? And I have no idea if it is using the language  that I specify or a default syntax highlighting ?
-cpede

**Comment by amroamroamro** [comment]
Prettify is not a tool for programming language detection!

Like I said above, if you don't explicitly specify a language-hint  `<pre class="prettyprint">..</pre>`, it uses a very simple heuristic:

- if the code looks like markup (e.g `<tag name="value" />`), it applies an HTML-like language handler
- otherwise it uses a generic language handler (which works passably for most C-like languages)

On the other hand, specifying a language-hint `<pre class="prettyprint lang-cpp">..</pre>` will use that one with no guessing..
 
---

To be more specific, the "generic" language handler recognizes the following constructs:

- common keywords from a few languages (`if`, `function`, `def`, `var`, etc..)
- C-style and shell-style comments (`// comment`, `/* comment */`, `# comment`)
- single/double-quoted strings and multiline strings (`"some \"escaped\" string"`)
- regex literals (`/a*b?c+/`)
- number literals (`3.14`)
- types for valid names starting with a capital letter (for example `MyClassName` as opposed to `some_variable`), after the so called [PascalCase][3] [naming convention][4].

The last point is the reason why `Group` and `Samples` were styled as `typ` in your example using the generic language handler, unlike the C language handler which doesn't use that rule as fallback but an explicit list for what it considers to be type names.

Ultimately if you want to know more, the source code of `prettify.js` is the authoritative reference (refer to the [`sourceDecorator` function][1] and the various calls to [`registerLangHandler`][2]).

[1]: https://github.com/google/code-prettify/blob/master/src/prettify.js#L876
[2]: https://github.com/google/code-prettify/blob/master/src/prettify.js#L1350
[3]: https://en.wikipedia.org/wiki/PascalCase
[4]: https://en.wikipedia.org/wiki/Naming_convention_(programming)
